spring:
    application:
        name: apihelper
    profiles:
        active: dev
    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/inter/, classpath:/public/, file:${spring.http.multipart.location}
    servlet:
        multipart:
            max-request-size: -1
            max-file-size: -1

server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
        min-response-size: 2048

# mybatis plus配置
mybatis-plus:
    global-config:
        db-config:
            id-type: id_worker_str
    mapper-locations: classpath:/mapper/*Mapper.xml