alter table `system_user` modify column `system_organization_id` char(50) comment '组织机构ID' not null default '';
alter table `system_user_role` modify column `system_user_id` char(50) comment '用户ID' not null default '', modify column `system_role_id` char(50) comment '角色ID' not null default '';
alter table `system_organization` modify column `parent_id` char(50) comment '父组织机构ID' not null default '', modify column `cmn_city_id` char(50) comment '地市ID' not null default '', modify column `cmn_district_id` char(50) comment '行政区域ID' not null default '';
alter table `system_dictionary` modify column `parent_id` char(50) comment '父数据字典ID' not null default '';
alter table `system_config` modify column `cmn_street_id` char(50) comment '街道ID' not null default '';
alter table `cmn_district` modify column `cmn_city_id` char(50) comment '地市ID' not null default '';
alter table `cmn_street` modify column `cmn_district_id` char(50) comment '行政区域ID' not null default '';
alter table `cmn_street_organization` modify column `cmn_street_id` char(50) comment '管辖街道ID' not null default '', modify column `system_organization_id` char(50) comment '所属监管部门ID' not null default '';
alter table `dis_company` modify column `cmn_street_id` char(50) comment '街道ID' not null default '';
alter table `dis_company_extend` modify column `dis_company_id` char(50) comment '企业ID' not null default '';
alter table `dis_supervise_meta` modify column `ori_supervise_meta_id` char(50) comment '初始检查表ID' not null default '';
alter table `dis_supervise_meta_item` modify column `dis_supervise_meta_id` char(50) comment '检查表ID' not null default '';
alter table `dis_supervise` modify column `dis_supervise_meta_id` char(50) comment '检查表ID' not null default '', modify column `dis_company_id` char(50) comment '企业ID' not null default '', modify column `supervise_checker_id` char(50) comment '检查人员ID' not null default '', modify column `ori_supervise_id` char(50) comment '原监督记录ID' not null default '';
alter table `dis_supervise_companion` modify column `dis_supervise_id` char(50) comment '监督记录ID' not null default '', modify column `system_user_id` char(50) comment '用户ID' not null default '';
alter table `dis_supervise_detail` modify column `dis_supervise_id` char(50) comment '监督记录ID' not null default '', modify column `dis_supervise_meta_item_id` char(50) comment '检查项ID' not null default '';
alter table `dis_supervise_random` modify column `dis_supervise_id` char(50) comment '监督记录ID' not null default '';
alter table `dis_supervise_uncompliant` modify column `dis_supervise_id` char(50) comment '监督记录ID' not null default '';
alter table `dis_task` modify column `cmn_street_id` char(50) comment '街道ID' not null default '', modify column `dis_supervise_meta_id` char(50) comment '检查表ID' not null default '';
alter table `dis_task_company` modify column `dis_task_id` char(50) comment '任务计划ID' not null default '', modify column `dis_company_id` char(50) comment '企业ID' not null default '';
